language: node_js

node_js:
  - 6.0.0
env:
  global:
    secure: JZ5bv4SAeTp4J9qaPoEdHuaxhe7Plsfbo0/rScB099lXnqNlXGsEIx0PtXDpFXHqkfFC0COu61IHaAyWnfUpo9lcBO/XqyuNPlKZKLH7ZvE1A/Dk/9GFmEFxZMGlWC1xQv5e9c8Wz2Xc5eEg5UuvKmjhU/d5ec9FCV6MqODQi1INSfFcjP+Tnn+XbP5mOGGuZlds8V5xvOlhqaGLs8r6kWuQg8UOMz0ZJ5ufmGyRvqx6tte1lVRwP6ERdPJTrFDqzhKMdAWyyzZyCI0xFe8YbcRNtkKtAtnBDhpOA2Ebh79amKDR/0y6yw0ufZeiyraRzg5gmGDDD5wJGKCbFMp04g/h5LCbn+LRZr47wsrs4rMOrYTLG+Rq/4qmCsTdx/d7lJ39UOSxkjgydMIXCjbNbCYyRmE+8giNskQozFlQu/jHP4prmhXoyNllQMEXFejxYtiaIH4EAH0GDeIU5P7Sm8fJl6eOr2qq2veH49qO/6DlPWvYlAXp30spf4qHzKAYCdQ/KKRE7QK0Hnh90XcKUwhv3D71r72cB5pE0+pp7Xzh59EWi1QZjUPSlMdq95/cfGNcM32tRBu46P2HefEg/rpeHtdGQlarfY1Hiy8WG4OCi7noeJLwL9G/i2SLg6t6RpbDG8FuCq85HHEQpbyyzxpaInn1SF+RDQ5x5nfmKv8=

before_deploy:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.6.15/terraform_0.6.15_linux_amd64.zip"
  - o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"
    on:
      repo: mdb/terraform-example
      branch: master
